// This file would typically be generated by Supabase CLI
// For now, we'll create a basic type definition

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      expenses: {
        Row: {
          id: string
          amount: number
          description: string
          category: string
          date: string
          created_at: string
          updated_at: string
          user_id: string
          notes: string | null
          tags: string[] | null
          payment_method: string | null
          is_recurring: boolean
          recurring_frequency: string | null
        }
        Insert: {
          id?: string
          amount: number
          description: string
          category: string
          date: string
          created_at?: string
          updated_at?: string
          user_id: string
          notes?: string | null
          tags?: string[] | null
          payment_method?: string | null
          is_recurring?: boolean
          recurring_frequency?: string | null
        }
        Update: {
          id?: string
          amount?: number
          description?: string
          category?: string
          date?: string
          created_at?: string
          updated_at?: string
          user_id?: string
          notes?: string | null
          tags?: string[] | null
          payment_method?: string | null
          is_recurring?: boolean
          recurring_frequency?: string | null
        }
      }
      categories: {
        Row: {
          id: string
          name: string
          icon: string | null
          color: string | null
          display_order: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          icon?: string | null
          color?: string | null
          display_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          icon?: string | null
          color?: string | null
          display_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      payment_methods: {
        Row: {
          id: string
          name: string
          icon: string | null
          display_order: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          icon?: string | null
          display_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          icon?: string | null
          display_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      expense_groups: {
        Row: {
          id: string
          title: string
          category_id: string
          payment_method_id: string
          date: string
          total_amount: number
          memo: string | null
          photo_urls: string[] | null
          user_id: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          category_id: string
          payment_method_id: string
          date: string
          total_amount?: number
          memo?: string | null
          photo_urls?: string[] | null
          user_id: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          category_id?: string
          payment_method_id?: string
          date?: string
          total_amount?: number
          memo?: string | null
          photo_urls?: string[] | null
          user_id?: string
          created_at?: string
          updated_at?: string
        }
      }
      expense_items: {
        Row: {
          id: string
          group_id: string
          item_name: string
          amount: number
          note: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          group_id: string
          item_name: string
          amount: number
          note?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          group_id?: string
          item_name?: string
          amount?: number
          note?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      profiles: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          email: string
          full_name: string | null
          avatar_url: string | null
          currency: string
          monthly_budget: number | null
        }
        Insert: {
          id: string
          created_at?: string
          updated_at?: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          currency?: string
          monthly_budget?: number | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          currency?: string
          monthly_budget?: number | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      create_expense_with_items: {
        Args: {
          p_title: string
          p_category_id: string
          p_payment_method_id: string
          p_date: string
          p_items: Array<{
            item_name: string
            amount: number
            note?: string
          }>
          p_memo?: string | null
          p_photo_urls?: string[]
        }
        Returns: string
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}